config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, expect: [:new, :edit, :destroy] do
    member do
      get :confirm # confirm action in audit_logs_controller
    end
  end

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do   # view static/homepage --> _admin -> pending_approval  --> create approve_post_path
      get :approve  # appove post by click on the approve button
    end             # create method approve in posts_controller.rb
  end


  devise_for :users
  root to: 'static#homepage'
end

app/views/shared/_admin_dropdown.html.erb
<li>
  <%= link_to 'Admin Dashboard', admin_root_path %>
</li>
<li class="divider"></li>

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <%= js add_gritter(flash[:notice], :image => :notice, :title => "Time Tracker App Notification", :sticky => false, :time => 2000) %>
<% elsif flash[:alert] %>
  <%= js add_gritter(flash[:alert], :image => :notice, :title => "Time Tracker App Alert", :sticky => false, :time => 2000) %>
<% else %>
  <%= js add_gritter(flash[:error], :image => :error, :title => "Time Tracker App Error", :sticky => false, :time => 2000) %>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class= '<%= active?(audit_logs_path) %>' >
  <%= link_to "Audit Log", audit_logs_path %>
</li>

app/views/shared/_employee_nav_item.html.erb
<li class= '<%= active?(posts_path) %>' >
  <%= link_to "Entries", posts_path %>
</li>

<li class= '<%= active?(new_post_path) %>' >
  <%= link_to "Submit Hours", new_post_path,
  id: 'new_post_from_nav'
  %>
</li>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1>Time Tracker</h1>
</div>

<!-- TODO -->
<% if current_user %>
  <ul class="custom-nav nav nav-pills nav-tabs">
  	<li class= <%= active?(root_path) %> >
  		<%= link_to "", root_path, class: 'glyphicon glyphicon-home' %>
  	</li>

  	<%= render 'shared/employee_nav_item' if employee? %>

    <%= render 'shared/audit_log_tab' if admin? %>

  	<li class="dropdown pull-right">
  		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Acount<strong class="caret"></strong></a>
  		<ul class="dropdown-menu">

    		<%= render 'shared/admin_dropdown' if admin? %>

  			<li>
  				<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  			</li>
  		</ul>
  	</li>
  </ul>
<% end %>
<!-- TODO -->